FROM node:14-alpine

WORKDIR /app
COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile --non-interactive && yarn cache clean

ARG NODE_ENV="production"
ARG PORT=3000
ARG CORS_WHITELIST_REGEXP=""
ARG GLOBAL_THROTTLE_TTL=""
ARG GLOBAL_THROTTLE_LIMIT=""
ARG GLOBAL_CACHE_TTL=""
ARG LOG_LEVEL=""
ARG LOG_FORMAT=""

ENV NODE_ENV=$NODE_ENV \
  PORT=$PORT \
  CORS_WHITELIST_REGEXP=$CORS_WHITELIST_REGEXP \
  GLOBAL_THROTTLE_TTL=$GLOBAL_THROTTLE_TTL \
  GLOBAL_THROTTLE_LIMIT=$GLOBAL_THROTTLE_LIMIT \
  GLOBAL_CACHE_TTL=$GLOBAL_CACHE_TTL \
  LOG_LEVEL=$LOG_LEVEL \
  LOG_FORMAT=$LOG_FORMAT

EXPOSE $PORT

COPY . .
RUN yarn build

CMD ["yarn", "start:prod"]
