export const DATA_BUS_PRIVATE_KEY = 'dataBusPrivateKey';
export const DATA_BUS_BALANCE_UPDATE_BLOCK_RATE = 50;
export const DATA_BUS_PRIVATE_KEY_CONFIG_PATH = 'WALLET_PRIVATE_KEY';
export const DATA_BUS_PROVIDER_CONFIG_PATH = 'EVM_CHAIN_DATA_BUS_PROVIDER_URL';
export const DATA_BUS_ADDRESS = 'DATA_BUS_ADDRESS';
export const DATA_BUS_REQUEST_TIMEOUT = 30_000;
