export const DATA_BUS_PRIVATE_KEY = 'dataBusPrivateKey';
export const DATA_BUS_BALANCE_UPDATE_BLOCK_RATE = 50;
export const DATA_BUS_PRIVATE_KEY_CONFIG_PATH = 'DATA_BUS_PRIVATE_KEY';
export const DATA_BUS_PROVIDER_CONFIG_PATH = 'DATA_BUS_PROVIDER_URL';
