export const DSM_CONTRACT_VERSION_4 = 4;
export const DSM_CONTRACT_VERSION_5 = 5;

export const DSM_CONTRACT_SUPPORTED_VERSIONS = [
  DSM_CONTRACT_VERSION_4,
  DSM_CONTRACT_VERSION_5,
] as const;

export const ERC1271_INTERFACE_ID = '0x1626ba7e';
