global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'council-daemon'
    static_configs:
      - targets: ['docker.for.mac.host.internal:3003']
remote_write:
  - url: https://localhost/api/v1/write
